# Generated by Django 5.1.3 on 2024-11-24 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(to='members.member')),
            ],
        ),
    ]
